/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ChartContent: typeof import('./src/components/ChartContent.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CustomFilterColumn: typeof import('./src/components/filterComponent/CustomFilterColumn.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FormAddJob: typeof import('./src/components/form/FormAddJob.vue')['default']
    FormMasterEfficiency: typeof import('./src/components/form/FormMasterEfficiency.vue')['default']
    FormMasterHoliday: typeof import('./src/components/form/FormMasterHoliday.vue')['default']
    FormMasterLine: typeof import('./src/components/form/FormMasterLine.vue')['default']
    FormMasterSam: typeof import('./src/components/form/FormMasterSam.vue')['default']
    FormMasterWorkday: typeof import('./src/components/form/FormMasterWorkday.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    ManualEFF: typeof import('./src/components/datatable/ManualEFF.vue')['default']
    ManualMP: typeof import('./src/components/datatable/ManualMP.vue')['default']
    MenuSetting: typeof import('./src/components/MenuSetting.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalAddManualEFF: typeof import('./src/components/modal/modalAddManualEFF.vue')['default']
    ModalAddManualMP: typeof import('./src/components/modal/modalAddManualMP.vue')['default']
    ModalAddType: typeof import('./src/components/modal/modalAddType.vue')['default']
    ModalConfigExpertType: typeof import('./src/components/modal/modalConfigExpertType.vue')['default']
    ModalManualEFF: typeof import('./src/components/modal/modalManualEFF.vue')['default']
    ModalManualMP: typeof import('./src/components/modal/modalManualMP.vue')['default']
    ModalTypeMap: typeof import('./src/components/modal/modalTypeMap.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OrderFromLine: typeof import('./src/components/datatable/OrderFromLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleRow: typeof import('./src/components/ScheduleRow.vue')['default']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    Type: typeof import('./src/components/datatable/Type.vue')['default']
    ViewCanvas: typeof import('./src/components/viewCanvas.vue')['default']
    ViewOrderDetails: typeof import('./src/components/details/ViewOrderDetails.vue')['default']
  }
}
