/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ChartContent: typeof import('./src/components/ChartContent.vue')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CustomFilterColumn: typeof import('./src/components/filterComponent/CustomFilterColumn.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FormAddJob: typeof import('./src/components/form/FormAddJob.vue')['default']
    FormMasterEfficiency: typeof import('./src/components/form/FormMasterEfficiency.vue')['default']
    FormMasterHoliday: typeof import('./src/components/form/FormMasterHoliday.vue')['default']
    FormMasterLine: typeof import('./src/components/form/FormMasterLine.vue')['default']
    FormMasterSam: typeof import('./src/components/form/FormMasterSam.vue')['default']
    FormMasterWorkday: typeof import('./src/components/form/FormMasterWorkday.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    MenuSetting: typeof import('./src/components/MenuSetting.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleRow: typeof import('./src/components/ScheduleRow.vue')['default']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    ViewCanvas: typeof import('./src/components/viewCanvas.vue')['default']
    ViewOrderDetails: typeof import('./src/components/details/ViewOrderDetails.vue')['default']
  }
}
